// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePort():Promise<string>;

export function GetPortsList():Promise<Array<string>>;

export function OpenPort(arg1:string,arg2:number):Promise<string>;

export function Send(arg1:string):Promise<string>;
