// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClosePort() {
  return window['go']['main']['App']['ClosePort']();
}

export function GetPortsList() {
  return window['go']['main']['App']['GetPortsList']();
}

export function OpenPort(arg1, arg2) {
  return window['go']['main']['App']['OpenPort'](arg1, arg2);
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}
